/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controller.PantallasController;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Cliente;
import model.Recibo;

/**
 *
 * @author Alejandro Rodríguez Lugo - 251622
 */
public class DetalleConsumeView extends javax.swing.JPanel {

    private Cliente cliente;

    /**
     * Creates new form DetalleConsumeView
     */
    public DetalleConsumeView(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
        lblNombre.setText(cliente.getNombre());
        lblMonto.setText(String.format("$%.2f", cliente.getTotalPagar()));
        lblConsumo.setText(cliente.getConsumoKwh() + " kWh");
        lblPeriodo.setText(cliente.getPeriodo());
        lblFecha.setText(cliente.getFechaLimite());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        txtTarjeta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblConsumo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        lblNombre.setText("jLabel1");

        lblMonto.setText("jLabel2");

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        jLabel1.setText("Datos de consumo: ");

        lblPeriodo.setText("jLabel2");

        jLabel3.setText("Total a pagar:");

        jLabel4.setText("Período:");

        jLabel2.setText("Consumo (khw)");

        lblConsumo.setText("jLabel5");

        jLabel5.setText("Fecha límite");

        lblFecha.setText("jLabel6");

        jLabel6.setText("Ingresa el número de tarjeta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(lblConsumo))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFecha)
                                    .addComponent(jLabel5)))
                            .addComponent(lblPeriodo))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblMonto)
                            .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNombre))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMonto)
                    .addComponent(lblPeriodo)
                    .addComponent(lblConsumo)
                    .addComponent(lblFecha))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(txtTarjeta))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        if (cliente.getTotalPagar() == 0) {
            JOptionPane.showMessageDialog(this, "El cliente ya ha pagado la luz");
            return;
        }
        String numeroTarjeta = txtTarjeta.getText().trim();
        String tarjetaLimpia = numeroTarjeta.replaceAll("\\s+", "");
        if (!tarjetaLimpia.matches("\\d{16}")) {
            JOptionPane.showMessageDialog(this, "La tarjeta debe contener exactamente 16 números.", "Error", JOptionPane.ERROR_MESSAGE);
            txtTarjeta.requestFocus();
            return;
        }
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        try {
            String fechaStr = cliente.getFechaLimite();
            LocalDate fechaLimite = LocalDate.parse(fechaStr, formatter);
            LocalDate hoy = LocalDate.now();
            if (hoy.isAfter(fechaLimite)) {
                long diasDeRetraso = ChronoUnit.DAYS.between(fechaLimite, hoy);
                double recargo = diasDeRetraso * 2.0;
                cliente.setTotalPagar(cliente.getTotalPagar() + recargo);
                JOptionPane.showMessageDialog(this, "Se le asigno un cargo extra por el retraso: $ " + recargo);
            }
        } catch (java.time.format.DateTimeParseException e) {
            System.out.println("Error: El formato de fecha en la base de datos es incorrecto.");
        }
        JOptionPane.showMessageDialog(this, "Pago realizado correctamente");
        Recibo nuevoRecibo = new Recibo(cliente, numeroTarjeta);
        if (this.getParent() instanceof javax.swing.JPanel) {
            javax.swing.JPanel contenedorPadre = (javax.swing.JPanel) this.getParent();
            ReciboView vistaRecibo = new ReciboView(nuevoRecibo);
            PantallasController.getInstance().cambiarPanel(contenedorPadre, vistaRecibo);
            cliente.setTotalPagar(0);
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    public JButton getBtnPagar() {
        return btnPagar;
    }

    public JTextField getTxtTarjeta() {
        return txtTarjeta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblConsumo;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JTextField txtTarjeta;
    // End of variables declaration//GEN-END:variables

}
